export const FETCH_TOPICS = Object.freeze({
    INITIAL: "FETCH_TOPICS_INITIAL",
    SUCCESS: "FETCH_TOPICS_SUCCESS",
    FAILURE: "FETCH_TOPICS_FAILURE"
});

export const FETCH_POSTS = Object.freeze({
    INITIAL: "FETCH_POSTS_INITIAL",
    SUCCESS: "FETCH_POSTS_SUCCESS",
    FAILURE: "FETCH_POSTS_FAILURE"
});

export const SEARCH_TOPICS = Object.freeze({
    INITIAL: "SEARCH_TOPICS_INITIAL",
    SUCCESS: "SEARCH_TOPICS_SUCCESS",
    FAILURE: "SEARCH_TOPICS_FAILURE"
});

export const APP = Object.freeze({
   SET_ERROR: "APP_SET_ERROR",
   SET_SHOWING_POSTS: "APP_SET_SHOWING_POSTS",
   SET_CURRENT_TOPIC: "APP_SET_CURRENT_TOPIC"
});